### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by naofum**
Hello!

### CODE REVIEW

**Comment by caarmen** [comment]
Thanks!  I'd like to mention you in the about screen.  Something like:
"Naofum, for the Japanese translations".  To do this, I'll need:

* The name you'd like to put there (naofum or your real name)
* The Japanese translation for this
* A link to your website (or your github page if you prefer).

**Comment by caarmen** [comment]
Could you also provide "translations" for `default_team_member1` and `default_team_member2`?  I'd just like any common first name for a male and female, in Japanese :)

Thanks!

**Comment by naofum** [comment]
Hi!
Translated default_team_member1 and 2 to Japanese.

I'm Naofumi Fukue (福江尚史) and please link to github page.

**Comment by caarmen** [comment]
Thanks!  One last question then, how can I translate this (for the about screen):
> "Naofumi Fukue, for the Japanese translation."

:)

**Comment by naofum** [comment]
Thanks!

(日本語訳 福江尚史)

**Pull request merged**
